### ISSUE TITLE
Etymology for "oryza"

### ISSUE THREAD

**Issue by mingshey** [helmadik/LewisShortLogeion#5]
Under the entry "oryza", the etymology of Greek origin is οπνζα instead of ορυζα. So it doesn't link to the proper entry in LSJ. It seems that something got mixed up due to similar glyphs between Latin and Greek scripts. I suspect similar cases are scattered over the lexicon.

**Comment by helmadik** [comment]
hi Mingshey, 
This error was corrected a while ago in the XML and no longer shows in Diogenes, philolog.us or Logeion (web; see image). However, we have not updated the Logeion iOS app in a while so perhaps you saw it there? In such a case, please consider the report a problem link within the app, so it's easier to see where the problem resides, but nevertheless: thank you! It is reports like this that have incrementally improved the data over time. 
![image](https://user-images.githubusercontent.com/7517297/154536133-e4043275-669d-4933-b7b9-c2e59e1e0785.png)
