### ISSUE TITLE
Plautus act-scene-line mess

### ISSUE THREAD

**Issue by helmadik** [helmadik/LewisShortLogeion#6]
https://github.com/Paul-McK/Plautus/  wrote out all the corresponding single line ##s for act-scene-line numbers in L&S

I am pasting in my written-out act-scene combos. 

Amphitryo ={'11': '153','12: '463', '12: '463', '13: '499', '21: '551', '22: '633', '31: '861', '32: '882', '33: '956', '34: '984', '41: '1009', '42: '1021', '43: '1035', '51: '1053', '52: '1131'}
Asinaria = {'11: '16', '12: '127', '13: '153', '21: '249', '22: '257', '23: '381', '24: '407', '31: '504', '32: '545', '33: '591', '41: '746', '42: '810', '51: '828', '52: '851'}
Aulularia = {'11: '40', '12: '79', '21: '120', '22: '178', '23: '268', '24: '280', '25: '327', '26: '350', '27: '363', '28: '371', '29: '398', '31: '406', '32: '415', '33: '449', '34: '460', '35: '475', '36: '537', '41: '587', '42: '608', '43: '624', '44: '628', '45: '661', '46: '667', '47: '682', '48: '701', '49: '713', '410': '731', '51: '808'}
Bacchides= {'11': '35', '12': '109', '21': '170', '22': '179', '23': '235', '31': '368', '32': '385', '33': '405', '34': '500', '35': '526', '36': '530', '41': '573', '42': '583', '43': '612', '44': '640', '45': '761', '46': '770', '47': '799', '48': '842', '49': '925', '410': '979', '411': '1076', '51': '1087', '52': '1120'}
Captivi = {'11': '69', '12': '110', '21': '195', '22': '251', '23': '361', '31': '461', '32': '498', '33': '516', '34': '533', '35': '659', '41': '768', '42': '781', '43': '901', '44': '909', '51': '922', '52': '954', '53': '978', '54': '998'}
Casina = {'11': '89', '21': '144', '22': '165', '23': '217', '24': '279', '25': '309', '26': '353', '27': '424', '28': '437', '31': '515', '32': '531', '33': '563', '34': '591', '35': '621', '36': '720', '41': '759', '42': '780', '43': '798', '44': '814', '51': '855', '52': '875', '53': '937', '54': '963'}
Cistellaria = {'11': '1', '12': '120', '13': '149', '21': '203', '22': '536', '23': '543', '31': '631', '41': '653', '42': '671', '51': '774'}
Curculio = {'11': '1', '12': '96', '13': '158', '21': '216', '22': '251', '23': '280', '31': '371', '41': '462', '42': '487', '43': '533', '44': '557', '51': '591', '52': '599', '53': '679'}
Menaechmi = {'11': '77', '12': '110', '13': '182', '14': '219', '21': '226', '22': '273', '23': '351', '31': '446', '32': '466', '33': '524', '41': '559', '42': '571', '43': '675', '51': '701', '52': '753', '53': '876', '54': '889', '55': '899', '56': '966', '57': '990', '58': '1050', '59': '1060'}
Pseudolus = {'11': '3', '12': '132', '13': '230', '14': '394', '15': '415', '21': '574', '22': '594', '23': '667', '24': '694', '31': '767', '32': '790', '41': '905', '42': '956', '43': '1017', '44': '1038', '45': '1052', '46': '1063', '47': '1103', '51': '1246', '52': '1285'}

**Comment by helmadik** [comment]
`<bibl n="Perseus:abo:phi,0119,006:5:2:41"><author>Plaut.</author> <title>Cas.</title> 5, 2, 41</bibl>`
change the tag not the text..

**Comment by helmadik** [comment]
![image](https://user-images.githubusercontent.com/7517297/194612935-64b7bb44-d34d-4370-b56f-3ef4830a802e.png)

**Comment by helmadik** [comment]
`<bibl n="Perseus:abo:phi,0119,006:**5:2:41**"><author>Plaut.</author> <title>Cas.</title> 5, 2, 41</bibl>; <bibl n="Perseus:abo:phi,0119,008:1:1:56"><author>id.</author> <title>Curc.</title> 1, 1, 56</bibl>`
replace the perseus citation ("CTS").

**Comment by helmadik** [comment]
•	"      Am. or Amph., Amphitruo. 0119,001
	•	"      As. or Asin., Asinaria.  0119,002
	•	"      Aul., Aulularia. 0119,003
	•	"      Bacch., Bacchides. 0119,004
	•	"      Capt., Captivi.0119,005
	•	"      Cas., Casina. 0119,006
	•	"      Cist., Cistellaria. 0119,007
	•	"      Curc., Curculio. 0119,008
	•	"      Ep. or Epid., Epidicus.  0119,009
	•	"      Men., Menaechmi.  0119,010
	•	"      Merc., Mercator.  0119,011
	•	"      Mil., Miles Gloriosus. 0119,012
	•	"      Most., Mostellaria. 0119,013
	•	"      Pers., Persa. 0119,014
	•	"      Poen., Poenulus. 0119,015
	•	"      Ps., Pseudolus. 0119,016
	•	"      Rud., Rudens. 0119,017
	•	"      Stich., Stichus. 0119,018 
	•	"      Trin., Trinummus. 0119,019
	•	"      Truc., Truculentus.0119,020

**Comment by gabigarc03** [comment]
Oops have been forgetting to link commits, but see the resolving-plautus-lines branch for more commits.

**Comment by gabigarc03** [comment]
Complete!! Will let you check over and close the issue.

**Comment by helmadik** [comment]
Hey! I did some checking in volume 1, and I think there were some scenes missing from Paul McKenna's listing. They show up as lines 0 in the file. Ditto for some prol lines but that is easy to fix. Not his fault! E.g. Trin. 2,4 is not in the text I have here either. Never mind, it is! I looked for 3.4.. 2.4.1 = 402

**Comment by helmadik** [comment]
Found some instances that should not be touched: if the attribute is 0119,0..:..." then we must have a line number (or something that can at least not be understood as act x, (scene y), line z). So if there is **only one number following the work**, it should be left alone. I've just added a bunch more to these by resolving the prologue line numbers, but this occurred at the end of the basilicus entry for instance. With the prologues done, and the line number for Trinummus 2.4 = 420, we should be in great shape for a second round. This has repaired 10s of thousands, so getting it in the low 200s would be great, and I think we're there with these changes. Uploading new files shortly.

**Comment by gabigarc03** [comment]
Gotcha, sounds good! Merged your PR.

**Comment by helmadik** [comment]
Do you think
  if len(tokens) < 4:  (continue)
should be 
 if len(tokens) < 5:

This would not mess with line ##s already calculated
Perseus:abo:phi,0119,006:237 = this is 4 items by my count, right, and the precalculated 237 is left alone? 


I don't think the script knows that if you have 5 items, it is act - line. So it doesn't get 
    elif act == 5:
        lineNum = line + 1393
(in Mil) and other sceneless acts. Curc,..

**Comment by helmadik** [comment]
Almost there! Volume 1 triage, leaving out duplicate Miles Act 5 examples, etc. 
x > y: x became y with parse_plaut. 

Group A: single-scene acts. 
Perseus:abo:phi,0119,007:3:10 >  Perseus:abo:phi,0119,007:0 (Cist)
Perseus:abo:phi,0119,007:5:4    >  Perseus:abo:phi,0119,007:0 (also Cist)
Perseus:abo:phi,0119,012:5:5  > Perseus:abo:phi,0119,012:0  (Miles)
Perseus:abo:phi,0119,012:1:78  > Perseus:abo:phi,0119,012:0 (Miles)
Perseus:abo:phi,0119,008:3:20 > Perseus:abo:phi,0119,008:0  (Curc)


Perseus:abo:phi,0119,015:2:11   > Perseus:abo:phi,0119,015:11 Poen. act 2 Different behavior? Would have expected 0.

Group B: only a token 4 is present. Leave completely as is. 

Perseus:abo:phi,0119,018:775 > Perseus:abo:phi,0119,018:0  (this was originally Stichus fin.: end of play: already repaired)
Same cite in text, (775) becomes (775) (0) :-) 
Perseus:abo:phi,0119,008:262  > Perseus:abo:phi,0119,008:0  filled in earlier, also becomes (262) (0)
Perseus:abo:phi,0119,011:87 > Perseus:abo:phi,0119,011:0 filled in earlier (prologue case)

**Comment by helmadik** [comment]
Have now cleaned up (I think) all zero references that were shady: wrong author, wrong title, typos.. There are a couple of cases where there are still ^0-9 characters. These are fragmentary works. Leave text as is, as with group B above.

**Comment by gabigarc03** [comment]
Gotcha, makes sense!

**Comment by gabigarc03** [comment]
Seeing something funky with Stichus - there are citations for act 2 scene 3, but the Plautus breakdown has no act 2 scene 3

**Comment by gabigarc03** [comment]
I think this is fixed now - please see the commit!

**Comment by helmadik** [comment]
Should have closed this a long time ago. Plautus citations now fullly modernized.
